# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memories', '0007_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mem',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
